import { Sora, Russo_One } from "next/font/google";
import { Header } from "@/components";
import "./globals.css";

const sora = Sora({
  subsets: ["latin"],
  display: "swap",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
  variable: "--ff-sora",
});
const russo = Russo_One({
  subsets: ["latin"],
  display: "swap",
  weight: ["400"],
  variable: "--ff-russo",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${sora.variable} ${russo.variable}`}>
      <body className="min-h-screen font-sora text-base text-slate-50 bg-secondary">
        <Header />
        {children}
      </body>
    </html>
  );
}

